version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
      - JWT_SECRET=thisisasamplesecret
      - JWT_ACCESS_EXPIRATION_MINUTES=30
      - JWT_REFRESH_EXPIRATION_DAYS=30
      - JWT_RESET_PASSWORD_EXPIRATION_MINUTES=10
      - JWT_VERIFY_EMAIL_EXPIRATION_MINUTES=10
      - SMTP_HOST=email-server
      - SMTP_PORT=587
      - SMTP_USERNAME=email-server-username
      - SMTP_PASSWORD=email-server-password
      - EMAIL_FROM=support@yourapp.com
    ports:
      - '3001:3000'
    depends_on:
      - mongodb
  
    container_name: node-app-prod
    command: yarn start
    networks:
      - node-network

  mongodb:
    image: mongo:4.2.1-bionic
    # ports:
    #   - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
